package com.opendatamask.domain.model

enum class SensitivityType {
    FIRST_NAME, LAST_NAME, FULL_NAME, EMAIL, PHONE,
    STREET_ADDRESS, ZIP_CODE, CITY, STATE, COUNTRY, POSTAL_CODE, GPS_COORDINATES,
    USERNAME, PASSWORD,
    CREDIT_CARD, IBAN, SWIFT_CODE, MONEY_AMOUNT, BTC_ADDRESS,
    SSN, PASSPORT_NUMBER, DRIVERS_LICENSE, BIRTH_DATE, GENDER,
    BIOMETRIC, ICD_CODE, MEDICAL_RECORD_NUMBER, HEALTH_PLAN_NUMBER,
    ACCOUNT_NUMBER, IP_ADDRESS, IPV6_ADDRESS, MAC_ADDRESS, URL,
    VIN, LICENSE_PLATE, ORGANIZATION,
    UNKNOWN
}
